# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.8', '3.9' ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Lint with flake8
      run: |
        python -m pip install flake8 flake8-bugbear flake8-commas flake8-import-order
        flake8 .
    - name: Test with pytest and generate coverage report
      run: |
        python -m pip install pytest pytest-cov
        pytest --cov --cov-report=xml -vv
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        env_vars: OS,PYTHON
        name: paxter-codecov
        verbose: true
    - name: Package sanity check
      run: |
        python -m pip install docutils check-manifest
        python setup.py check --strict --metadata
        check-manifest
